### ISSUE TITLE
Azure B2C Tenant

### ISSUE THREAD

**Issue by nagydavid** [jamesholcombe/dash-auth-external#22]
HI I am trying use this module, but I have a bit of a problem of customising it to the Azure B2C - Oath2.0 Authentication.
(https://github.com/Azure-Samples/ms-identity-python-webapp)
With the above implementation, the authentication routing is failing for me.

I wondering, have you experimented withe the Azure B2C authentication flow?

Best 

David

**Comment by jamesholcombe** [comment]
Hi, I haven't used azure B2C. Can you post a reproducable example? On which request is the error occuring, the /authorize or the /token endpoint?

**Comment by nagydavid** [comment]
Hi @jamesholcombe 

Just a little background. In my organization, we have a global login implemented using Azure B2C Tenant(Oath2.0). 

As a flask app I can do the same what Microsoft refers in the above link.

So by using the `identity` library, I am creating the `Auth` object, which should handle the token retrieval and authentication.
```
auth = identity.web.Auth(
    session=session,
    authority=app.config.get("AUTHORITY"),
    client_id=app.config["CLIENT_ID"],
    client_credential=app.config["CLIENT_SECRET"],
)
```

Routing of the app to the global login URL. See comments.
```
@app.route("/")
def index():
    # if not signed in
    if not auth.get_user():
       # getting the URI based on the scope
        auth_url = auth.log_in(
            scopes=app_config.SCOPE,  # Have user consent to scopes during log-in
            redirect_uri=url_for("auth_response", _external=True),
        )
        #getting the token based on the scope
        auth.get_token_for_client(scopes=app_config.SCOPE)
        #redirecting to GLOBAL LOGIN
        return redirect(auth_url["auth_uri"])

    return render_template(
        "index.html", user=auth.get_user(), version=identity.__version__
    )
```
The `app_config.REDIRECT_PATH` is `localhost:5000/getAToken`

```
@app.route(app_config.REDIRECT_PATH)
def auth_response():
    result = auth.complete_log_in(request.args)
    if "error" in result:
        return render_template("auth_error.html", result=result)
    return redirect(url_for("index"))

```
Your solution:

So I am using your sample app with the substitute of the URLs from Azure.
```
AUTH_URL = "https://logint.xxxxxxx.com/xxxxxxxxxxxx.onmicrosoft.com/b2c_1a_signingf/oauth2/v2.0/authorize"
TOKEN_URL = "https://logint.xxxxxxx.com/xxxxxxxxxxx.onmicrosoft.com/b2c_1a_signingf/oauth2/v2.0/token"
CLIENT_ID = "xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxxx"
```
 I am getting an error here, because I can't  figure out what suppose to be the 
`FLASK_SESSION_TOKEN_KEY ` . So I receive the value error `valueError("No token found in request session.")`

```
def _get_token_data_from_session() -> dict:
    """Gets the token data from the session.

    Returns:
        dict: The token data from the session.
    """
    token_data = session.get(FLASK_SESSION_TOKEN_KEY)
    if token_data is None:
        raise ValueError("No token found in request session.")
    return token_data
```

**Comment by nagydavid** [comment]
Ok, so I so my mistake when I used your app. I forgot to specify the `scope` and the `redirect_uri`. 

I managed to redirect to the global login, but now I getting an error `The request to the access token endpoint failed.`
 The error log:
```
 * Serving Flask app 'dash_auth_external.auth'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
Press CTRL+C to quit
127.0.0.1 - - [24/Apr/2023 12:04:41] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [24/Apr/2023 12:04:57] "GET / HTTP/1.1" 302 -
[2023-04-24 12:05:32,466] ERROR in app: Exception on /getAToken [GET]
Traceback (most recent call last):
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/davidnagy/Documents/private/dash-auth-external/dash_auth_external/routes.py", line 110, in get_token_route
    response_data = token_request(
  File "/Users/davidnagy/Documents/private/dash-auth-external/dash_auth_external/routes.py", line 129, in token_request
    raise requests.RequestException(
requests.exceptions.RequestException: 400 Bad Request:The request to the access token endpoint failed.
127.0.0.1 - - [24/Apr/2023 12:05:32] "GET /getAToken?state=S78vhhT7SOv9XmQ3M1eWZcLxu4ti2Y&code=eyJraWQiOiJNZE4xSnAzWmhxbG53OVdhZjB3MjVSX1U4dUwzUUVZR010WGZZaHpkNHJ3IiwidmVyIjoiMS4wIiwiemlwIjoiRGVmbGF0ZSIsInNlciI6IjEuMCJ9.B7LtcvlWFoN8EC9Ju7HXgypXWZMKKQyLoVqZrmd3hj_vo9lWGDmjf3LIx7-nzuHLcMidAqsZA9-YgW_pfuWxl8eUzLGD7S1o0AengVzcfj2oLcPxQrUQUb38bwRIBpNK1yz1rBg5iNoOfD8uCsUACU3LYq7Om4E2ShukOsPIOLv2P-AdGCPZ3DQcqEA0FUtYcgn21eQ9uGxwnVFlobx-gFgwVGAraLFG_i6n7T7NqqQppeagDxyz1NE-TfS6FuNsgnC3uIXjUe6CVS9MU2ezTwJw7A7K4MyjxCTwNwduEEx5GWzlYRpV9aDp2XK6iTSWlxq5S2AcbNslAOSEmoeuEg.9PX0H9imrGKEjviN.omIl7h8NQu3Gz3w6NFvXI1tU34pkc3yqqmiac1PggentmvClPuyPJomOZgEna4ShYZ5q5kmFll0aSYao31dGO0H2Dq7nOJwIZ_RfoJtQnCZiYrNRBiVrjnBozgbsqqXvPCnaG4qS-i3KcNdr6y6DFJwrBT_5ncFDcvFlS8Oh74wdLkHn3oW1KPlUNdBXi1mOFoWR8nnW2WAhT1sIjfNcrh2nDxACnUlyw9ig4HckbeoibkJNdB1leQ0BPiSppjayksjTS1wNxPB9CB8gCd7ei4sCbLBKRJ7aYfmfeuiYLlPQN05kwW2ylrXDQmOAQjhFKD7-dEraMwW9iMzPQn_eXsB9tvoABvMh3e2r20MTioc204hbF9k38vpGn83kbcgnsn3AYUjeeGm2pf-9L1FkTaaPBxV-XaHimi9XmJPqeT06EfMNrbe2uL0fudT7Aqluj3tjFWKpCghXnrWjUYdPA-iVn6T3WoGuWd-G5jD_-HOKMCCxZYMNwXDhqEL8DvAWg42aRgKpG2wjLCQOOVkFXkAiS7YqB_hBcqxO6o-OXqPw1LnUQpVcSkNux-ta2O74yrryO278kiOlwGEt83rHhIt1WYN7lzTGi7bazsx17aRNWvpaIzaGLocsCKRPiBNYDzgyouioM-Z89PYfCiVrlZju4NgxK3BHJ47WCfuTMouMF-DQwFJq-iq3XHIB_xKqw0wX4bOTNxSrtYj8eXaP9_ym_DeyroopG1Y3I1VzEaoYx_Piu--v_Z7xc57A6Qw0YTT432UkKraiu3c46HnYP78d_cncY7i5hN82S6yP3lzldEBMOYix3ogIg7gKGIhj9hUJG_LrHu3z_cgcgVyI6TnEjgfQPKnZRnb-E8HDgBane5M-lVcZcPP7RByyY5dipe0kOhXkxS8s796iFHX3t3t22uOy-gJmswwK9MXGMz9GWcjgtmphoVbdYbihBDyIWCUb_iOMZQHU3HpZcg0rQ5-tHWjTpnGFnDM8WuLUvAGk5YNx9x5Tvv-n_lTUkLMRRPZdiRnqKRnaMD0XTLNl9q8MGldPSFS9GrvVFo_qBJ2q6goZRNyjgpuLjeQGIf9NS678oA.Gytv-ODh3UT-7G-lLTib1Q HTTP/1.1" 500 -
```

**Comment by nagydavid** [comment]
Sorry for commenting a lot, kinda documenting my process.

So it seems I reached the main issue, which I thought originally. where can I pass my client_secret.

because the request sends me back the following.:
`'{"error":"invalid_request","error_description":"AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.\\r\\nCorrelation ID: 0a9846a6-c85f-4d61-a98c-3bc8b734af72\\r\\nTimestamp: 2023-04-24 10:55:34Z\\r\\n"}'
`

**Comment by jamesholcombe** [comment]
Ah okay. This is an oversight on my behalf. Client secret needs to be sent to the token endpoint. The body for the request is defined here.
https://github.com/jamesholcombe/dash-auth-external/blob/40dafb6f8e97812c2064154d78a856a486dfb61b/dash_auth_external/routes.py#L69-L88

I will draft a release in the next few days, otherwise feel free to put in a PR.

In the meantime, I would clone the repo, and amend this code to include your secret.

**Comment by nagydavid** [comment]
I already have made some changes :), if you want I can make a PR.
```
def build_token_body(url: str, redirect_uri: str, client_id: str, with_pkce: bool):
    query = urllib.parse.urlparse(url).query
    redirect_params = urllib.parse.parse_qs(query)
    code = redirect_params["code"][0]
    state = redirect_params["state"][0]
    body = dict(
        grant_type="authorization_code",
        code=code,
        redirect_uri=redirect_uri,
        client_id=client_id,
        state=state,
    )
    if os.getenv("CLIENT_SECRET"):
        body["client_secret"] = os.getenv("CLIENT_SECRET")

    if with_pkce:
        body["code_verifier"] = session["cv"]

    return body
```
, but I also have some issue, because the response content someway different and therefore the Oath2Token class ill throw an error.

So might be an Oauth2Token should be provider specific casing.

Response from Azure:
`dict_keys(['access_token', 'token_type', 'not_before', 'expires_in', 'expires_on', 'resource', 'profile_info', 'scope'])`

Also it is interesting. When I start up the application, for the first call of the URL  (localhost:8050), I get the following error, 
```
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'dash_auth_external.auth'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8050
Press CTRL+C to quit
127.0.0.1 - - [24/Apr/2023 14:24:10] "GET / HTTP/1.1" 302 -
[2023-04-24 14:24:11,921] ERROR in app: Exception on /getAToken [GET]
Traceback (most recent call last):
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/davidnagy/Documents/private/dash-auth-external/dash_auth_external/routes.py", line 104, in get_token_route
    body = build_token_body(
  File "/Users/davidnagy/Documents/private/dash-auth-external/dash_auth_external/routes.py", line 85, in build_token_body
    body["code_verifier"] = session["cv"]
  File "/Users/davidnagy/Documents/private/dash-auth-external/.venv/lib/python3.10/site-packages/flask/sessions.py", line 80, in __getitem__
    return super().__getitem__(key)
KeyError: 'cv'
```

When I refresh the page, it will go through.

**Comment by jamesholcombe** [comment]
yep PR would be great, I'd prefer if client secret was defined as an optional kwarg to the main Auth object, which then gets passed down explicitally, rather than relying on env vars.

regarding the azure response, according to https://datatracker.ietf.org/doc/html/rfc6749#section-5.1, the client should ignore other params, so I'd suggest that the instantiation of OAuth2 token should use explicit params, rather than **kwargs as it does at present. 

https://github.com/jamesholcombe/dash-auth-external/blob/40dafb6f8e97812c2064154d78a856a486dfb61b/dash_auth_external/routes.py#L110-L118

If you need access to the actual response data (for user profile data etc), I think storing the response in  another session cookie could work. Which could then be exposed as a method on the auth object.

**Comment by jamesholcombe** [comment]
interesting on first load failing. Without digging into it, I'd assume a race condition ..

**Comment by nagydavid** [comment]
@jamesholcombe , I just had the time to look into, it seems, the session becomes empty after `redirect(authorization_url)`
it looks like the session is lost and and cv cannot be verified
